# NOME DO WORKFLOW
name: Generate Snake Animation

# PERMISSÕES PARA A ACTION LER SEUS DADOS DE CONTRIBUIÇÃO
permissions:
  contents: read

# EVENTOS QUE DISPARAM A ACTION (AGENDAMENTO E MANUAL)
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# TAREFAS QUE A ACTION VAI EXECUTAR
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # PASSO 1: BAIXA O CÓDIGO DO SEU REPOSITÓRIO
      - name: Checkout
        uses: actions/checkout@v3

      # !!! PASSO NOVO ADICIONADO AQUI PARA CRIAR A PASTA !!!
      - name: Create dist directory
        run: mkdir -p dist

      # PASSO 2: GERA O ARQUIVO SVG DA COBRA USANDO A VERSÃO MAIS RECENTE
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Davifilippini
          # Adicionada a linha abaixo para usar a animação de texto garantida
          from_url: https://raw.githubusercontent.com/Platane/snk/output/snek-dark.svg
          svg_out_path: dist/github-contribution-grid-snake.svg

      # PASSO 3: ENVIA O ARQUIVO GERADO PARA O BRANCH 'output'
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
